customhost = "projectswarna.ceju5bfe0v7b.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin1234"
customdb = "projectswarna"
custombucket = "projectswarna"
customregion = "us-east-1"
